### ISSUE TITLE
Update the DataSet labeling routine to correctly label metrics

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug-vtk#44]
The current routine for determining the name of the data set is here:

https://github.com/ladybug-tools/ladybug-vtk/blob/2e7d5c827e8b2a190564bfac17d0eb59615c4738/ladybug_vtk/polydata.py#L168-L177

It has a couple of issues.

First, if the data set has a `data_set.legend_parameters.title`, then this means that there is a title that the user has selected themselves to override the default title from the `data_set.data_type`. So this legend parameter title should take precedence for this case.

Second, when there is no `data_type` specified or title specified in the legend parameters, this means that the legend should not have any title. For example, when you have a stacked bar chart of energy balances where each color refers to a different term and there's no need to label the whole legend. So the `generic_data` in the code linked above should probably just be an empty string or something that similarly denotes that there is no title.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey, I'm closing this issue since it seems to be related to the viewer itself and not ladybug-vtk. I wrote a longer response on Basecamp. Feel free to re-open the issue if needed.
